# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 700)
        MainWindow.setMinimumSize(QtCore.QSize(640, 700))
        MainWindow.setMaximumSize(QtCore.QSize(640, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textUtilisateur = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.textUtilisateur.setGeometry(QtCore.QRect(10, 630, 521, 41))
        self.textUtilisateur.setObjectName("textUtilisateur")
        self.envoyer = QtWidgets.QPushButton(self.centralwidget)
        self.envoyer.setGeometry(QtCore.QRect(540, 630, 71, 41))
        self.envoyer.setObjectName("envoyer")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(13, 20, 591, 601))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.envoyer.setText(_translate("MainWindow", "Envoyer"))
