alter table chatbot
add Qimage blob;


create table aideExo( 
idEx integer, 
idAide integer, 
CONSTRAINT kf_ex FOREIGN KEY (idEx) REFERENCES exercice(idEx),
CONSTRAINT fk_aide FOREIGN KEY (idAide) REFERENCES aide(idAide), 
CONSTRAINT pk_aideexo PRIMARY KEY (idEx,idAide));

create table grotMot(
idGM integer primary key,
mot varchar(50));

insert into exercice VALUES
(15,"Trouvez le bon mot de l'image affichée. ","vache",2,"cp","BDD/ImageExo/bonMot1.PNG"),
(16,"Trouvez le bon mot de l'image affichée. ","renard",2,"cp","BDD/ImageExo/bonMot2.PNG"),
(17,"Trouvez le bon mot de l'image affichée. ","cheval",2,"cp","BDD/ImageExo/BonMot3.PNG"),
(18,"Quel est la distance entre la marre, passant par le totem puis la foret  et le chateau ? ","270",1,"ce1","BDD/ImageExo/calculDistance.PNG"),
(19,"Quel est la distance entre les maisons et la foret en passant par la marre puis les cailloux et le totem ? ","305",1,"ce1","BDD/ImageExo/calculDistance.PNG"),
(20,"Quel est la distance la plus courte pour aller des maisons jusqu'au chateaux ? ","340",1,"ce1","BDD/ImageExo/calculDistance.PNG"),
(21,"Combien de mot <<chouette>> il y a dans la grille ? ","3",2,"ce2","BDD/ImageExo/combienEcrit1.PNG"),
(22,"Combien de mot <<hibou>> il y a dans la grille ? ","3",2,"ce2","BDD/ImageExo/combienEcrit2.PNG"),
(23,"Quel est la coordonnee de la ville de Paris ? ","(D,5)",1,"ce1","BDD/ImageExo/coordoneeVille.PNG"),
(24,"Quel est la coordonnee de la ville de Marseille ? ","(J,6)",1,"ce1","BDD/ImageExo/coordoneeVille.PNG"),
(25,"Quel est la coordonnee de la ville de Bordeaux ? ","(H,3)",1,"ce1","BDD/ImageExo/coordoneeVille.PNG"),
(26,"Ecrivez la phrase dans le bon ordre. ","Dans le garage, la voiture est à l'abri.",2,"ce1","BDD/ImageExo/phraseMelange.PNG"),
(27,"Ecrivez la phrase dans le bon ordre. ","Nous partirons visiter l'Espagne en juillet prochain.",2,"ce1","BDD/ImageExo/phraseMelange2.PNG");

INSERT INTO aide VALUES
(4,"Pensez à l'addition.",1),
(5,"Faites bien attention à regarder horisontalement, verticalement, diagonalement et a l'envers.",2),
(6,"Rappelez vous bien de la syntaxe d'une coordonnée, il ce trouve entre parenthese, par exemple (z,8).",1),
(7,"Regardez bien la ponctuation cela pourrait vous ader.",2);

INSERT INTO aideexo VALUES
(1,1),
(11,3),
(12,3),
(13,3),
(14,3),
(3,2),
(18,4),
(19,4),
(20,4),
(21,5),
(22,5),
(23,6),
(24,6),
(25,6),
(26,7),
(27,7);

INSERT INTO grotmot VALUES
(1,"merde"),
(2,"caca"),
(3,"méchant"),
(4,"t'as gueule"),
(5,"abruti"),
(6,"chian"),
(7,"singe"),
(8,"con"),
(9,"putain"),
(10,"emmerde"),
(11, "pute"),
(12, "conne"),
(13, "connasse"),
(14, "ane"),
(15, "avorton"),
(16, "barjo"),
(17, "batard"),
(18, "bete"),
(19, "sexe"),
(20, "clampin"),
(21, "connard"),
(22, "crétin"),
(23, "crapule"),
(24, "débile"),
(25, "cul"),
(26, "déguelasse"),
(27, "crétin"),
(28, "enculé"),
(29, "espece de"),
(30, "espèce de"),
(31, "enflure"),
(32, "enfoiré"),
(33, "fumier"),
(34, "gland"),
(36, "idiot"),
(37, "imbécile"),
(38, "imbecile"),
(39, "lache"),
(40, "maboul"),
(41, "malandrin"),
(42, "maudit"),
(44, "misérable"),
(46, "naze"),
(47, "obsédé"),
(48, "ordure"),
(49, "pouf"),
(50, "punaise"),
(51, "relou"),
(52, "saligaut"),
(54, "salopart"),
(56, "salopiaud"),
(57, "sous-merde"),
(58, "tafiole"),
(59, "tapette"),
(60, "trainé"),
(61, "vaurien"),
(62, "ferme la"),
(64, "baise"),
(66, "porno"),
(67, "porn"),
(68, "sex"),
(69, "boobs"),
(70, "sexy"),
(71, "baisé"),
(72, "encule"),
(76, "enculer"),
(77, "connerie"),
(78, "branle"),
(79, "bander"),
(80, "branler");
